//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string Name { get; set; }
        public string header { get; set; }
        public string content { get; set; }
        public System.DateTime dateGive { get; set; }
        public System.DateTime dateDeadLine { get; set; }
    }
}
