//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotFamiliarDocuments
    {
        public string user_Login { get; set; }
        public string names_DocumentsList { get; set; }
    
        public virtual User User { get; set; }
    }
}
