//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientMetro.MetroService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://MetroService/", ConfigurationName="MetroService.MetroServiceSoap")]
    public interface MetroServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetroService/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Ping(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetroService/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PingAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetroService/GetUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUsers(string sekret_key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetroService/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetUsersAsync(string sekret_key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetroService/GetDocuments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDocuments(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://MetroService/GetDocuments", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDocumentsAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MetroServiceSoapChannel : ClientMetro.MetroService.MetroServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetroServiceSoapClient : System.ServiceModel.ClientBase<ClientMetro.MetroService.MetroServiceSoap>, ClientMetro.MetroService.MetroServiceSoap {
        
        public MetroServiceSoapClient() {
        }
        
        public MetroServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetroServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetroServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetroServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping(string login, string password) {
            return base.Channel.Ping(login, password);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string login, string password) {
            return base.Channel.PingAsync(login, password);
        }
        
        public string GetUsers(string sekret_key) {
            return base.Channel.GetUsers(sekret_key);
        }
        
        public System.Threading.Tasks.Task<string> GetUsersAsync(string sekret_key) {
            return base.Channel.GetUsersAsync(sekret_key);
        }
        
        public string GetDocuments(string login, string password) {
            return base.Channel.GetDocuments(login, password);
        }
        
        public System.Threading.Tasks.Task<string> GetDocumentsAsync(string login, string password) {
            return base.Channel.GetDocumentsAsync(login, password);
        }
    }
}
